######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 2 17:40:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h ../openglqt/render.h customlabel.h
SOURCES += main.cpp
QT += opengl

RESOURCES += \
    res.qrc

OTHER_FILES += \
    images/temp2.png \
    images/temp.png
